language: python
python:
    - "2.7"
install:
    - pip install -qr requirements.txt
    - pip install coveralls
script: ./test.sh
after_success:
    coveralls
deploy:
  provider: pypi
  user: edx
  password:
    secure: Jx4zxLqiy16+zkeJw0FLlwFJNGlxfJLVxAaGbDMohrGO98EVvD4wivvGnybqAq65wqlbPVq3uFijV/ozqaRFCGnK/jdQy4QLdeUfJNBfdCFBDyzUGCWKt5lhX8/FNftWO85DX1I+FnlI9KVR8AU9veNVww2yMXVgt85WCR0aox0=
  distributions: sdist bdist_wheel
  on:
    tags: true
