language: python
python:
    - "2.7"
install:
    - pip install -qr requirements.txt
    - pip install coveralls
script: ./test.sh
after_success:
    coveralls
deploy:
  provider: pypi
  user: edx
  password:
    secure: G8N7hXGl4a9J6pwLVbniGBgz0I2qA4sHTamSw++8HrJO5QCYnYBZQr25BpdrbE83UJX+pDdLxVj85+fML5XlrSf/hlc4XQTYMHcLhVQNNIjEim5q9hlKkBi+wwCErm5U9UZwzfvFbNx/w9SSO4qAM2NUbTP0fEZ/wF8Od2bJNVc=
  distributions: sdist bdist_wheel
  on:
    tags: true
